### ISSUE TITLE
最近的master版本会报这个

### ISSUE THREAD

**Issue by zhushiqiang** [smartwalle/ncrypto#1]
../../../../../../github.com/smartwalle/ncrypto/key.go:82:6: undefined: any
../../../../../../github.com/smartwalle/ncrypto/key.go:86:43: undefined: any
../../../../../../github.com/smartwalle/ncrypto/key.go:177:6: undefined: any
../../../../../../github.com/smartwalle/ncrypto/key.go:181:40: undefined: any

**Comment by smartwalle** [comment]
升级一下你的 go 吧
